### ISSUE TITLE
Incompatible with C2ME

### ISSUE THREAD

**Issue by MatiCugno69** [marlester-dev/twilightforest-unofficial#1]
### Fabric Loader Version

0.16.5

### Fabric API Version

0.92.2+1.20.1

### Twilight Forest Version

1.2 STABLE

### Client Log

https://gist.github.com/MatiCugno69/409daca683d6c12bfaccbd219e78cfd5

### Steps to Reproduce

1 - Have both C2ME version "0.2.0+alpha.11.13 devbuild for 1.20.1" and Twilight Forest Unofficial 1.2 STABLE in the mods folder.
2 - Launch the game.

### What You Expected

The game launches normally.

### What Happened Instead

Got a Fabric loader error popup expressing that Twilight Forest Unofficial is incompatible with c2me. This happens as soon as the player launches the game.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by CaoTrongThang** [comment]
I've been getting this error too, hope it'll be fixed. Thank you for creating this mod for fabric

**Comment by CaoTrongThang** [comment]
@marlester-dev can you take a look at this, really hope you can support the mod

**Comment by marlester-dev** [comment]
> @marlester-dev can you take a look at this, really hope you can support the mod

Please update to the latest version, it should be fixd

**Comment by CaoTrongThang** [comment]
> > @marlester-dev can you take a look at this, really hope you can support the mod
> 
> Please update to the latest version, it should be fixd

nice, it's fixed
