### ISSUE TITLE
blocks turns into overwoldblock and crashes when a specific mob spawned

### ISSUE THREAD

**Issue by DragonlordRozza** [marlester-dev/twilightforest-unofficial#3]
### Fabric Loader Version

0.16.5

### Fabric API Version

0.92.2+1.20.1

### Twilight Forest Version

1.20.1-1.2

### Client Log

https://gist.github.com/DragonlordRozza/79a73150da3e7515380df3b7e78759f2

### Crash Report (if applicable)

https://gist.github.com/DragonlordRozza/881a3ac3029ad7129a9a7c321818dc12

### Steps to Reproduce

First go to Twilight Forest brake some block
Second it turns the block that you leftclick into overworld block and rightclick changes it back to normal
Third if a boar spawn it crashes the game

### What You Expected

that i can brake the blocks and does the mobs normal without any issue

### What Happened Instead

cant brake blocks and collect them and that the twilights mobs crashes the game (sorry for the bad English im german)

### Additional Details

[Modlist.txt](https://github.com/user-attachments/files/17348288/Modlist.txt)
https://drive.google.com/file/d/1Q7PvfWy2OSPCRHqtdwJE0fx4QqakVgia/view?usp=drive_link (modlist)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by DragonlordRozza** [comment]
i try it with only your mod block error but if i leave the world and enter it agin it work but if i go twilight or overworld is the same block error
![Bild_2024-10-12_083721314](https://github.com/user-attachments/assets/0fdcf6f8-93e7-4488-b764-5449c289c65c)
![Bild_2024-10-12_083812224](https://github.com/user-attachments/assets/7f622224-c49b-4f77-a98d-b7a82544f7f5)
https://drive.google.com/file/d/1l5_49IF38CdOiB-LEqTjvEqgMsXf71yc/view?usp=sharing

this fix works for the modpack modified (privat use) too

**Comment by marlester-dev** [comment]
Moin!
Danke für den Bug-Report. Es wird noch etwas dauern, bis alle Bugs gefixt sind.

**Comment by marlester-dev** [comment]
der Bug mit dem Portal ist gefixt worden (im nächsten Release ist der fix schon drinne)
aber das ist mit dem boar (wildschwein) muss ich noch anschauen

**Comment by DragonlordRozza** [comment]
ich musste in dem Charm Mod eine Pig Setting ändern und dann hat es geklappt

**Comment by marlester-dev** [comment]
Inkompatibilität hinzugefügt:
Charm Forked:
    Lösung: PigsFindMushrooms in Konfiguration ausmachen
    Grund: Dieser Mod injiziert direkt die Mob-Modelle, die TwilightForestUnofficial verwendet
    Alternative vorgeschlagen: https://www.curseforge.com/minecraft/mc-mods/earth2java
