### ISSUE TITLE
Mod causing -1 error (some sort of incompatibility)

### ISSUE THREAD

**Issue by gigibyte-art** [marlester-dev/twilightforest-unofficial#5]
### Fabric Loader Version

0.16.7

### Fabric API Version

0.92.2

### Twilight Forest Version

1.2 STABLE

### Client Log

https://gist.github.com/gigibyte-art/7c221662f84d418dc732d655ad018a7f

### Steps to Reproduce

1. use curseforge launcher with fabric and my modpack 2. open game from launcher and wait 3. see the white window for minecraft 4. window closes, launcher opens, see -1 code "failed to initialize"

### What You Expected

expected the mod to work as it did when it was independantly launched

### What Happened Instead

game crashed with error -1

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by marlester-dev** [comment]
I don't see the error in the logs

**Comment by marlester-dev** [comment]
error -1 is too vague, I need the error log

**Comment by marlester-dev** [comment]
closing due inactivity
